import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { Inter, Roboto } from 'next/font/google'
import SideBar from "@/components/templates/sidebar";
import { Toaster } from "@/components/ui/toaster";

export const inter = Inter({subsets: ['latin'], weight: ['700', '500']})
export const roboto = Roboto({subsets: ['latin'], weight: ['700', '500']})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased flex`}//${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <SideBar/> */}
        {/* <main className="min-h-screen bg-white flex flex-col p-14 flex-1"> */}
          {children}
          <Toaster />
        {/* </main> */}
      </body>
    </html>
  );
}
