import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { Inter, Roboto } from 'next/font/google'
import SideBar from "@/components/templates/sidebar";

export const inter = Inter({subsets: ['latin'], weight: ['700', '500']})
export const roboto = Roboto({subsets: ['latin'], weight: ['700', '500']})
/* const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
}); */

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} flex`}//${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SideBar/>
        {children}
      </body>
    </html>
  );
}
