import type { Metadata } from "next";
import SideBar from "@/components/templates/sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
        <SideBar/>
        {/* <main className="min-h-screen bg-white flex flex-col p-14 flex-1"> */}
          {children}
        {/* </main> */}
    </>
  );
}
